import AppKit
import SwiftUI
import UniformTypeIdentifiers

struct MainView: View {
    @EnvironmentObject private var viewModel: AppViewModel
    @AppStorage(AppConstants.showMenuBarIconDefaultsKey) private var showMenuBarIcon = false

    var body: some View {
        ZStack {
            mainContent
            InstallOverlay(coordinator: viewModel.installCoordinator)
        }
        .confirmationDialog(
            "Flags were reapplied",
            isPresented: Binding(
                get: { viewModel.pendingRelaunchTarget != nil },
                set: { if !$0 { viewModel.clearRelaunchPrompt() } }
            )
        ) {
            Button("Relaunch") {
                viewModel.relaunchPendingTarget()
            }
            Button("Not Now", role: .cancel) {
                viewModel.clearRelaunchPrompt()
            }
        } message: {
            Text("Roblox or Studio appears to have updated and replaced the generated flag file.")
        }
        .confirmationDialog(
            "Replace existing settings?",
            isPresented: Binding(
                get: { viewModel.pendingReplacement != nil },
                set: { if !$0 { viewModel.cancelReplacement() } }
            )
        ) {
            Button("Replace and Launch") {
                viewModel.confirmReplacement()
            }
            Button("Cancel", role: .cancel) {
                viewModel.cancelReplacement()
            }
        } message: {
            Text("The selected app already has a ClientAppSettings.json file that was not generated by MacRo. It will be backed up before replacement.")
        }
    }

    private var mainContent: some View {
        VStack(spacing: 0) {
            header
            Divider()
            content
            Divider()
            footer
        }
        .frame(minWidth: 880, minHeight: 560)
    }

    private var header: some View {
        HStack(spacing: 12) {
            Picker("Target", selection: $viewModel.selectedTarget) {
                ForEach(TargetKind.allCases) { target in
                    Text(target.displayName).tag(target)
                }
            }
            .pickerStyle(.segmented)
            .frame(width: 280)

            Spacer()

            Toggle("Show menu bar icon", isOn: $showMenuBarIcon)
                .toggleStyle(.checkbox)

            Button("Import JSON") {
                importJSON()
            }

            Button("Export JSON") {
                exportJSON()
            }
        }
        .padding(16)
    }

    private var content: some View {
        VStack(alignment: .leading, spacing: 10) {
            FlagTableView(
                rows: viewModel.bindingRows(for: viewModel.selectedTarget),
                isApplying: viewModel.isApplying
            )

            let validation = viewModel.validationSummary(for: viewModel.selectedTarget)
            if !validation.isEmpty {
                Text(validation)
                    .font(.callout)
                    .foregroundStyle(.red)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
        .padding(16)
    }

    private var footer: some View {
        HStack(spacing: 12) {
            Button(AppConstants.quitButtonTitle) {
                AppRuntime.shared.isQuittingFromExplicitAction = true
                NSApp.terminate(nil)
            }

            if let error = viewModel.errorMessage {
                Text(error)
                    .foregroundStyle(.red)
                    .lineLimit(2)
            } else {
                Text(viewModel.statusMessage.isEmpty ? "Ready" : viewModel.statusMessage)
                    .foregroundStyle(.secondary)
                    .lineLimit(2)
            }

            Spacer()

            if viewModel.canUninstall(viewModel.selectedTarget) {
                Button(viewModel.selectedTarget == .roblox ? "Uninstall Roblox" : "Uninstall Studio", role: .destructive) {
                    viewModel.uninstall(viewModel.selectedTarget)
                }
                .disabled(viewModel.isApplying)
            }

            Button(launchButtonTitle) {
                viewModel.applyAndLaunchSelectedTarget()
            }
            .keyboardShortcut(.return, modifiers: [.command])
            .disabled(viewModel.isApplying)
        }
        .padding(16)
    }

    private var launchButtonTitle: String {
        let target = viewModel.selectedTarget
        let verb = viewModel.isInstalled(target) ? "Launch" : "Install"
        return target == .roblox ? "\(verb) Roblox" : "\(verb) Studio"
    }

    private func importJSON() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.json]
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        if panel.runModal() == .OK, let url = panel.url {
            do {
                let data = try Data(contentsOf: url)
                viewModel.setRows(try FlagImporting.rows(from: data), for: viewModel.selectedTarget)
                viewModel.saveRows(for: viewModel.selectedTarget)
            } catch {
                viewModel.errorMessage = error.localizedDescription
            }
        }
    }

    private func exportJSON() {
        do {
            let data = try FlagSerializer.serialize(viewModel.rows(for: viewModel.selectedTarget))
            let panel = NSSavePanel()
            panel.nameFieldStringValue = "ClientAppSettings.json"
            panel.allowedContentTypes = [.json]
            if panel.runModal() == .OK, let url = panel.url {
                try data.write(to: url, options: [.atomic])
            }
        } catch {
            viewModel.errorMessage = error.localizedDescription
        }
    }
}
